---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}

rm(list=ls())
setwd("C:/Documents/R Files/Advent of Code")
source("C:/Documents/R Files/Setup.R")

```

```{r}

# Setup ----
input <- readLines(str_c("Inputs/advent 25.txt"))

snafu_table <- tibble(
  digit=-2:2,
  snafu=c("=", "-", "0", "1", "2")
)

# Functions ----
to_snafu <- function(num) {
  remaining_num <- num
  string <- ""
  for (power in 22:0) {
    temp <- tibble(remaining_num) %>%
      crossing(snafu_table) %>%
      mutate(
        value=(5^power) * digit,
        diff=remaining_num - value,
        abs_diff=abs(diff)
      ) %>%
      filter(abs_diff == min(abs_diff))
    
    string <- str_c(string, temp %>% pull(snafu))
    remaining_num <- temp %>% pull(diff)
  }
  str_sub(
    string,
    str_locate(string, "[^0]")[1]
  )
}

# Part one ----
input %>%
  as_tibble() %>%
  mutate(
    rn=row_number(),
    max=max(str_length(value)),
    value=str_pad(value, max, "left", "0")
  ) %>%
  separate(value, as.character(c(-1L, ((.) %>% pullfirst(max) %>% { . - 1L }):0)), sep="") %>%
  select(-c(`-1`, max)) %>%
  pivot_longer(-rn, names_to="column") %>%
  mutate(
    column=5^as.numeric(column),
    value=case_when(
      value == "-" ~ "-1",
      value == "=" ~ "-2",
      TRUE ~ value
    ) %>%
      as.integer(),
    col_amount=column * value
  ) %>%
  group_by(rn) %>%
  summarise(amount=sum(col_amount)) %>%
  summarise(total=sum(amount)) %>%
  deframe() %>%
  to_snafu()

```


